# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rp <- function(n, k, alpha, C, m) {
    .Call('_CKMR_rp', PACKAGE = 'CKMR', n, k, alpha, C, m)
}

eigenMapMatMult <- function(A, B) {
    .Call('_CKMR_eigenMapMatMult', PACKAGE = 'CKMR', A, B)
}

eigenQuadProd <- function(A, B) {
    .Call('_CKMR_eigenQuadProd', PACKAGE = 'CKMR', A, B)
}

